services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: test
    shm_size: '2g'
    ports:
      - 127.0.0.1:40112:5432
    command:
      - 'postgres'
      - '-c'
      - 'fsync=off'
      - '-c'
      - 'shared_buffers=1024MB'
      - '-c'
      - 'synchronous_commit=off'
      - '-c'
      - 'full_page_writes=off'
      # - "-c"
      # - "log_statement=all"
      - '-c'
      - 'max_connections=1000'
